name: Data Pipeline Execution

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'  # Exécute le script chaque jour à midi UTC

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install pandas requests

      - name: Execute Data Pipeline
        run: python data_pipeline.py

      - name: Upload Output File
        uses: actions/upload-artifact@v3
        with:
          name: output_data
          path: output_data.csv
