name: Data Pipeline Execution

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'  # Exécute tous les jours à midi UTC

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install pandas requests matplotlib seaborn fpdf

      - name: Check if data_pipeline.py exists
        run: |
          if [ ! -f "data_pipeline.py" ]; then echo "❌ ERREUR : Fichier data_pipeline.py introuvable"; exit 1; fi
          echo "✅ Fichier trouvé, exécution en cours..."

      - name: Execute Data Pipeline
        run: python data_pipeline.py
