name: Data Pipeline Execution

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * *'  # Exécute tous les jours à midi UTC

jobs:
  run_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Mise à jour de v3 à v4

      - name: Set up Python
        uses: actions/setup-python@v5  # Mise à jour de v4 à v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install pandas requests matplotlib seaborn fpdf

      - name: Execute Data Pipeline
        run: python data_pipeline.py

      - name: Execute Data Visualization
        run: python data_visualization.py

      - name: Upload Reports and Graphs
        uses: actions/upload-artifact@v4  # Mise à jour de v3 à v4
        with:
          name: visualization_report
          path: |
            data_report.pdf
            category_distribution.png
            https_support.png
